
enum CLIENT_EVENTS
{

    // com 1
    COM_RADIO_WHOLE_DEC,
    COM_RADIO_WHOLE_INC,
    COM_RADIO_FRACT_DEC,
    COM_RADIO_FRACT_INC,
    COM_STBY_RADIO_SWAP,

    // com2
    COM2_RADIO_WHOLE_DEC,
    COM2_RADIO_WHOLE_INC,
    COM2_RADIO_FRACT_DEC,
    COM2_RADIO_FRACT_INC,
    COM2_RADIO_SWAP,

    // nav1
    NAV1_RADIO_WHOLE_DEC,
    NAV1_RADIO_WHOLE_INC,
    NAV1_RADIO_FRACT_DEC,
    NAV1_RADIO_FRACT_INC,
    NAV1_RADIO_SWAP,

    // nav2
    NAV2_RADIO_WHOLE_DEC,
    NAV2_RADIO_WHOLE_INC,
    NAV2_RADIO_FRACT_DEC,
    NAV2_RADIO_FRACT_INC,
    NAV2_RADIO_SWAP,

};